ExNihilo\GuildBundle\Entity\Presentation:
    type: entity
    table: null
    repositoryClass: ExNihilo\GuildBundle\Repository\PresentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
    lifecycleCallbacks: {  }
