ex_nihilo_platform_blog:
    path:     /
    defaults: { _controller: ExNihiloPlatformBundle:Blog:index }

security_login:
    path:     /login
    defaults: { _controller: ExNihiloUserBundle:Security:login }

security_logout:
    path:     /logout
    defaults: { _controller: ExNihiloUserBundle:Security:logout }

user_register:
    path:     /register/
    defaults: { _controller: ExNihiloUserBundle:User:register }

ex_nihilo_platform_presentation:
    path:     /presentation
    defaults: { _controller: ExNihiloPlatformBundle:Presentation:index }

ex_nihilo_platform_members:
    path:     /members
    defaults: { _controller: ExNihiloPlatformBundle:Members:index }

ex_nihilo_platform_events:
    path:     /events
    defaults: { _controller: ExNihiloPlatformBundle:Events:index }


article_view:
    path:     /article/{id}/view
    defaults: { _controller: ExNihiloBlogBundle:Article:view }

event_view:
    path:     /event/{id}/view
    defaults: { _controller: ExNihiloEventBundle:Event:view }


ex_nihilo_article_admin_classe:
    resource: "@ExNihiloPlatformBundle/Resources/config/routing/classe.yml"
    prefix:   /admin/classe