services:
    manage_classe:
        class:        ExNihilo\PlatformBundle\Character\ManageClasse
        arguments:
            ["@doctrine.orm.entity_manager", "@form.factory", "@router"]

    manage_race:
        class:        ExNihilo\PlatformBundle\Character\ManageRace
        arguments:
            ["@doctrine.orm.entity_manager", "@form.factory", "@router"]
