services:
    manage_presentation:
        class:        ExNihilo\GuildBundle\Presentation\ManagePresentation
        arguments:
            ["@doctrine.orm.entity_manager", "@form.factory", "@router"]