<?php

namespace ExNihilo\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getUserswithEvent($eventId)
    {
        $qb = $this->createQueryBuilder('e');


        $qb
            ->innerJoin('e.users', 'u')
            ->addSelect('u')
        ;

        $qb->where($qb->expr()->in('e.id', $eventId));

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function checkEvent($eventId, $userId)
    {
        $qb = $this->createQueryBuilder('e');

        $qb
            ->innerJoin('e.users', 'u')
            ->select('e')
            ->addSelect('u')
        ;
        $qb
            ->where($qb->expr()->in('e.id', $eventId))
            ->andWhere($qb->expr()->in('u.id', $userId))
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
