<?php

namespace ExNihilo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getGuildMembers($classeId)
    {

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.classe = :classeId')
            ->andWhere('u.isGuildMember = :isGuildMember')
            ->addOrderBy('u.username')
            ->setParameter('classeId', $classeId)
            ->setParameters(array('isGuildMember' => 1, 'classeId' => $classeId));

        return $qb->getQuery()
            ->getResult();
    }
}
